directories:
  output: release
  buildResources: resources
productName: Bolt
appId: org.develar.ElectronReact
files:
  - filter:
      - dist/
      - node_modules/
      - app.html
      - main.prod.js
      - main.prod.js.map
      - package.json
dmg:
  contents:
    - x: 130
      'y': 220
    - x: 410
      'y': 220
      type: link
      path: /Applications
win:
  target:
    - nsis
    - msi
linux:
  target:
    - deb
    - rpm
    - AppImage
  category: Development
publish:
  provider: github
  repo: bolt
  private: false
electronVersion: 8.4.1
